name: Publish

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy- Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
     Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.UNIXFLOW }}
          username: ${{ secrets.FTP_FLOW }}
          password: ${{ secrets.FTP_UNIX }}
          local-dir: ./
          server-dir: /home/topdialn/unix/
