name: Publish

on:
  push:
    branches:
      - main

jobs:
  deploy-website: # Unique job name
    name: FTP-Deploy-Website to CPanel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # or v3
        with:
          fetch-depth: 0 # often a good idea if you want to deploy everything
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: sftp:/${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Or a more specific path like ./build or ./dist
          server-dir: /home/topdialn/unix/ # or remote-dir if that's how your server is set up.
