name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: sftp://${{ secrets.UNIXFLOW }}
          username: ${{ secrets.FTP_FLOW }}
          password: ${{ secrets.FTP_UNIX }}
          local-dirThe failure in your GitHub Actions job is due to an incorrect FTP server configuration. The error message: ./
          server-dir: /topdial-real/
