name: Publish Website to cPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP Deployment to cPanel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0  # Updated to latest version
        with:
          ftp-server: ${{ secrets.UNIXFLOW }}  
          ftp-username: ${{ secrets.FTP_FLOW }}  
          ftp-password: ${{ secrets.FTP_UNIX }}
          local-dir: ./                         
          server-dir: /home/topdialn              
          git-ftp: true
          dangerous-clean-slate: true           # Cleans server directory first
          ftp-passive: true                     # Enable passive mode
